# See config.example.yml for documentation.
object: orig/D43J01/sys/main.dol
hash: 7e785ecf59e526ed0c87492f05af06a1265bb06a
symbols: config/D43J01/symbols.txt
splits: config/D43J01/splits.txt
mw_comment_version: 8
