# See config.example.yml for documentation.
object: orig/mq-j/main.dol
hash: 7e785ecf59e526ed0c87492f05af06a1265bb06a
symbols: config/mq-j/symbols.txt
splits: config/mq-j/splits.txt
mw_comment_version: 8

extract:
- symbol: discerror
  header: discerror.inc # RARC archive
